# iCE40 Async Adder (Chisel) - OSS CAD Suite build
# Reference: https://github.com/jasonwaseq/FPGA-RISC-V-5-Stage-Pipelined-Processor
#
# OSS CAD Suite (Linux/WSL). Override with: make OSS_CAD_SUITE=/other/path ...
OSS_CAD_SUITE ?= /home/jasonwaseq/oss-cad-suite
export PATH := $(OSS_CAD_SUITE)/bin:$(PATH)

# Directories
RTL_DIR = src/rtl/chisel-verilog
BUILD_DIR = build
CONSTRAINTS_DIR = constraints
TESTS_DIR = tests
SCRIPTS_DIR = scripts

# Top module (UART bridge + async adder for iCEBreaker)
TOP_MODULE = Top
RTL_TOP = $(RTL_DIR)/Top.v
ECHO_TOP = TopEcho
RTL_ECHO = $(RTL_DIR)/TopEcho.v

# FPGA settings (iCEBreaker - iCE40UP5K-SG48)
DEVICE = up5k
PACKAGE = sg48
PCF_FILE = $(CONSTRAINTS_DIR)/icebreaker.pcf
FREQ = 12

# Chisel: Scala sources (triggers RTL regeneration when changed)
SCALA_SRC = $(shell find src -name '*.scala' 2>/dev/null)

#-------------------------------------------------------------------------------
# RTL generation (Chisel -> Verilog)
#-------------------------------------------------------------------------------
.PHONY: rtl
rtl: $(RTL_TOP)

$(RTL_TOP): $(SCALA_SRC)
	@mkdir -p $(RTL_DIR)
	@command -v java >/dev/null 2>&1 || { echo "Error: java not found. Install JDK in WSL: sudo apt install openjdk-11-jdk"; exit 127; }
	sbt "runMain add.Top"

$(RTL_ECHO): $(SCALA_SRC)
	@mkdir -p $(RTL_DIR)
	sbt "runMain add.TopEcho"

#-------------------------------------------------------------------------------
# Synthesis (Yosys + nextpnr-ice40 + icepack)
#-------------------------------------------------------------------------------
.PHONY: build synth place route prog prog-flash

$(BUILD_DIR)/$(TOP_MODULE).json: $(RTL_TOP)
	@mkdir -p $(BUILD_DIR)
	yosys -q -p "read_verilog $<; synth_ice40 -top $(TOP_MODULE); write_verilog $(BUILD_DIR)/$(TOP_MODULE)_syn.v; write_json $@"

$(BUILD_DIR)/$(TOP_MODULE).asc: $(BUILD_DIR)/$(TOP_MODULE).json $(PCF_FILE)
	nextpnr-ice40 --$(DEVICE) --package $(PACKAGE) \
		--pcf-allow-unconstrained \
		--json $(BUILD_DIR)/$(TOP_MODULE).json \
		--pcf $(PCF_FILE) \
		--asc $@ \
		--freq $(FREQ)

$(BUILD_DIR)/$(TOP_MODULE).bin: $(BUILD_DIR)/$(TOP_MODULE).asc
	icepack $< $@

# Echo build (minimal UART loopback for validation)
$(BUILD_DIR)/$(ECHO_TOP).json: $(RTL_ECHO)
	@mkdir -p $(BUILD_DIR)
	yosys -q -p "read_verilog $<; synth_ice40 -top $(ECHO_TOP); write_json $@"

$(BUILD_DIR)/$(ECHO_TOP).asc: $(BUILD_DIR)/$(ECHO_TOP).json $(PCF_FILE)
	nextpnr-ice40 --$(DEVICE) --package $(PACKAGE) \
		--pcf-allow-unconstrained \
		--json $(BUILD_DIR)/$(ECHO_TOP).json \
		--pcf $(PCF_FILE) \
		--asc $@ \
		--freq $(FREQ)

$(BUILD_DIR)/$(ECHO_TOP).bin: $(BUILD_DIR)/$(ECHO_TOP).asc
	icepack $< $@

.PHONY: build-echo prog-echo test-echo
build-echo: $(RTL_ECHO) $(BUILD_DIR)/$(ECHO_TOP).bin
prog-echo: $(BUILD_DIR)/$(ECHO_TOP).bin
	iceprog $<
test-echo:
	python3 $(SCRIPTS_DIR)/uart_echo_test.py /dev/ttyUSB1

synth: $(BUILD_DIR)/$(TOP_MODULE).json
place: $(BUILD_DIR)/$(TOP_MODULE).asc
build: rtl $(BUILD_DIR)/$(TOP_MODULE).bin

# Program FPGA (OSS CAD Suite iceprog)
prog: $(BUILD_DIR)/$(TOP_MODULE).bin
	iceprog $<

prog-flash: prog

#-------------------------------------------------------------------------------
# Simulation (ADD testbench)
#-------------------------------------------------------------------------------
.PHONY: sim
sim: $(RTL_DIR)/ADD.v
	@mkdir -p $(BUILD_DIR)/sim
	cd $(BUILD_DIR)/sim && \
	iverilog -o ADD_tb.vvp -s ADD_tb ../../$(TESTS_DIR)/ADD_tb.v ../../$(RTL_DIR)/ADD.v && \
	vvp ADD_tb.vvp

# ADD.v is generated by sbt run (default main is add.ADD)
$(RTL_DIR)/ADD.v: $(SCALA_SRC)
	@mkdir -p $(RTL_DIR)
	sbt run

#-------------------------------------------------------------------------------
# FPGA testing (UART adder). Run from WSL if board is attached via WSL.
# Rebuild bitstream after RTL changes (e.g. UART.scala fix): make build && make prog
#-------------------------------------------------------------------------------
.PHONY: test-fpga test-fpga-interactive test-fpga-debug test-fpga-debug-script
test-fpga:
	python3 $(SCRIPTS_DIR)/uart_adder_test.py

test-fpga-interactive:
	python3 $(SCRIPTS_DIR)/uart_adder_test.py -i

test-fpga-debug:
	python3 $(SCRIPTS_DIR)/uart_adder_test.py -d -v

test-fpga-debug-script:
	python3 $(SCRIPTS_DIR)/uart_adder_debug.py /dev/ttyUSB1

#-------------------------------------------------------------------------------
# Clean
#-------------------------------------------------------------------------------
.PHONY: clean clean-all
clean:
	rm -rf $(BUILD_DIR)
	rm -f *.vcd *.fst

clean-all: clean
	rm -rf $(RTL_DIR)/*.v $(RTL_DIR)/*.fir

#-------------------------------------------------------------------------------
# Help
#-------------------------------------------------------------------------------
.PHONY: help
help:
	@echo "iCE40 Async Adder (Chisel + OSS CAD Suite)"
	@echo ""
	@echo "RTL:"
	@echo "  make rtl     - Generate Verilog (sbt runMain add.Top) -> $(RTL_DIR)/Top.v"
	@echo ""
	@echo "Synthesis (iCEBreaker):"
	@echo "  make build   - RTL + Yosys + nextpnr + icepack -> $(BUILD_DIR)/$(TOP_MODULE).bin"
	@echo "  make prog    - Program FPGA with iceprog"
	@echo ""
	@echo "Simulation:"
	@echo "  make sim     - Run ADD testbench (iverilog + vvp)"
	@echo ""
	@echo "FPGA test:"
	@echo "  make test-fpga           - UART adder automated tests"
	@echo "  make test-fpga-interactive - Interactive A+B via UART"
	@echo "  make test-fpga-debug     - UART tests with debug timestamps/bytes"
	@echo ""
	@echo "Other:"
	@echo "  make clean   - Remove build artifacts"
	@echo ""
	@echo "Requires: sbt, OSS CAD Suite (yosys, nextpnr-ice40, icepack, iceprog, iverilog)."
	@echo "OSS_CAD_SUITE=$(OSS_CAD_SUITE)  (override: make OSS_CAD_SUITE=/path ...)"
